package Daje::Plugin::Signup;
use Mojo::Base 'Mojolicious::Plugin', -signatures;
use v5.40;

our $VERSION = "0.01";

#
# NAME
#
# Daje::Plugin::Signup - It's new $module
#
# SYNOPSIS
#
#     use Daje::Plugin::Signup;
#
# DESCRIPTION
#
# Daje::Plugin::Signup is ...
#
# LICENSE
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

sub register ($self, $app, $config) {

    $app->log->debug("Daje::Plugin::Signup::register start");

}

1;
__END__




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Plugin::Signup


=head1 DESCRIPTION


NAME

Daje::Plugin::Signup - It's new $module

SYNOPSIS

    use Daje::Plugin::Signup;

DESCRIPTION

Daje::Plugin::Signup is ...

LICENSE

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

AUTHOR

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 REQUIRES

L<v5.40> 

L<Mojo::Base> 


=head1 METHODS

=head2 register

 register();


NAME

Daje::Plugin::Signup - It's new $module

SYNOPSIS

    use Daje::Plugin::Signup;

DESCRIPTION

Daje::Plugin::Signup is ...

LICENSE

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

AUTHOR

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>




=cut

